### ISSUE TITLE
definition of has subsequence

### ISSUE THREAD

**Issue by sbello** [oborel/obo-relations#602] opened 2022-04-22 16:42 UTC
The definition of has subsequence (http://purl.obolibrary.org/obo/RO_0002524) is:

x has subsequence y iff all of the sequence parts of x are sequence parts of y

shouldn't this be

x has subsequence y iff all of the sequence parts of **y** are sequence parts of **x**

**Comment by balhoff** [comment] 2023-01-17 19:39
Duplicate of #206.

**Closed by balhoff** 2023-01-17 19:39 UTC
Labels: change request
