### ISSUE TITLE
NR: has exemplar, subcluster_of

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#485] opened 2021-08-05 15:25 UTC
We need a relation  'has exemplar' with a particular use for the cell ontology (and the brain data standards ontology) to link a cell type to a cluster from sc transcriptomics. The general pattern may be useful elsewhere.

For the clustering use case we may want relations like subcluster_of (taking RO into information artefacts, where haven't gone so far), so we can define property-chains such as 'has exemplar'  <- 'has exemplar'  o subcluster_of

This is closely related to an existing relation 'has prototype' http://purl.obolibrary.org/obo/RO_0002214

 * rdfs:label "has prototype"@en
 * definition "x has prototype y if and only if x is an instance of C and y is a prototypical instance of C. For example, every instance of heart, both normal and abnormal is related by the has prototype relation to some instance of a \"canonical\" heart, which participates in blood circulation."
 * 'editor note' "Experimental. In future there may be a formalization in which this relation is treated as a shortcut to some modal logic axiom. We may decide to obsolete this and adopt a more specific evolutionary relationship (e.g. evolved from)"
 * 'editor note' "This property can be used to make weaker forms of certain relations by chaining an additional property. For example, we may say: retina SubClassOf has_prototype some 'detection of light'. i.e. every retina is related to a prototypical retina instance which is detecting some light. Note that this is very similar to 'capable of', but this relation affords a wider flexibility. E.g. we can make a relation between continuants."
 * 'example of usage' "'human p53 protein' SubClassOf some ('has prototype' some ('participates in' some 'DNA repair'))"
 * 'example of usage' "heart SubClassOf 'has prototype' some ('participates in' some 'blood circulation')"

**Comment by cmungall** [comment] 2021-08-05 15:37
There is a general pattern here of a TBox classification mirroring an ABox tree, where the ABox tree represents in some sense prototypes, exemplars, canonical instances, etc.

We have two object properties in the following patterns connecting two bipartitle graphs

 * 'has_prototype' : connects the TBox or world of "real, variable" biology to prototypes instances via Equiv hasValue
 * 'prototypical_subtype_of: connects the ABox graph

[table below still being fleshed out]

|use case|has prototype relation|ABox domain|subtyping relation|cite
|---|---|---|---|---|
|cell classification from scSeq|has exemplar| clusters | subcluser_of |TODO

**Comment by patrick-lloyd-ray** [comment] 2021-09-02 19:25
I suppose I’ll jump in here with my thoughts: I think this is a good point, @wdduncan, and some clarification would help. I didn’t think of `prototype` in the way described by your link, but closer to the lexical semantic sense (Rosch). Similarly, I thought of the lexical semantic sense of `exemplar` (Nosofsky). 

These senses would (very roughly) be something like:

`prototype`: a single instance of a member of a category that is an abstract ideal.  

`exemplar`: an actual member(s) of a category that is typically representative of members of that category.  

In category theory (from what I understand, which is not much), prototypes are typically abstract entities and exemplars are typically concrete. There is almost always only one prototype for a category and typically more than one exemplar for a category. I’m sure there are other differences (again, not an expert by any means), but I don’t know they are relevant here. 

So, I think the `has_exemplar` relation is correct for the scSeq example when thought of in this way. Thoughts?

**Comment by wdduncan** [comment] 2021-09-02 23:47
@patrick-lloyd-ray Thanks for the clarification of the different senses for `prototype` and `exemplar` used in category theory. I was not aware of these :)

So, in these senses, would a reference genome be an exemplar (assuming the reference genome is a concrete individual)?

**Comment by cboelling** [comment] 2021-09-03 10:37
> closer to the lexical semantic sense (Rosch). Similarly, I thought of the lexical semantic sense of `exemplar` (Nosofsky).

@patrick-lloyd-ray Could you provide more detail for the references to "Rosch", "Nosofsky" and category theory (URIs or bibliographic detail)? Thanks!

**Comment by patrick-lloyd-ray** [comment] 2021-09-04 00:33
@wdduncan It seems so, although I'd defer to @cmungall on this. I'm not sure that what I've said was intended by the proposal, but your question was a good one and made me think about how one should approach this. 

@cboelling No problem! I think the most cited are: Rosch, E. (1975). Cognitive Representations of Semantic Categories. _Journal of Experimental Psychology: General_ 104: 192-232.

Rosch, E. and C.B. Mervis. (1975). Family Resemblances: Studies in the Internal Structure of Categories. _Cognitive Psychology_ 7: 573-605. 

Nosofsky, R.M. (1988). Exemplar-Based Accounts of Relations between Classification, Recognition, and Typicality. _Journal of Experimental Psychology: Learning, Memory and Cognition_ 14: 700-708. 

Without endorsing the work as a whole or the conclusions contained therein, I think that Lakoff has a nice and short historical summary of category theory in the opening chapters of "Women, Fire, and Dangerous Things" (ISBN:0-226-46804-6).

**Comment by nlharris** [comment] 2021-11-03 18:44
so can this ticket be closed?

**Comment by shawntanzk** [comment] 2021-11-03 19:44
yes, sorry, totally forgot to close it

**Closed by shawntanzk** 2021-11-03 19:44 UTC
Labels: new term request
